apiVersion: v1
kind: Service

metadata:
  name: dcgm-exporter
  namespace: llm-serving
  labels:
    app: dcgm-exporter

spec:
  type: ClusterIP

  selector:
    app: dcgm-exporter

  ports:
    - name: metrics
      protocol: TCP
      port: 9400
      targetPort: metrics
