apiVersion: v1
kind: Namespace
metadata:
  name: vllm-service
  namespace: llm-serving

spec:
  type: ClusterIP

  selector:
    app: vllm

  ports:
    - name: http
      port: 8000
      targetPort: 8000
